apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: basic-node-js
  namespace: badhikar
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: purple-mermaid-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: basic-node-js
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: basic-node-js-
      labels:
        build.appstudio.openshift.io/application: purple-mermaid-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: basic-node-js
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: badhikar
    spec:
      params:
      - name: git-url
        value: https://github.com/nodeshift-starters/devfile-sample.git
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:badhikar-basic-node-js-$(tt.params.git-revision)
      - name: dockerfile
        value: Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:861e28f4eb2380fd1531ee30a9e74fb6ce496b9f
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: basic-node-js/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
